apiVersion: v1
kind: Pod
metadata:
  name: lmcs-2020-timefluid-experiments
spec:
  restartPolicy: OnFailure
  containers:
  - image: docker.pkg.github.com/danysk/experiment-2020-lmcs-timefluid/lmcs2020-timefluid:latest
    name: lmcs-2020-timefluid-experiments-container
    env:
    - name: GITHUB_USERNAME
      value: DanySK
    - name: GITHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: github-packages-danysk-readonly
          key: token
    command: [ "/bin/sh" ]
    args: ["-c", "./gradlew runAllBatch && ./autogit; sleep 30d" ]
  imagePullSecrets:
  - name: github-registry-danysk-readonly
